config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'dashboard/index'
  devise_for :users
  root to: 'pages#home' # landing page => bike show

  resources :bikes do
    resources :bookings, only: [:new, :create ]
  end

  resources :reviews, only: [ :show, :update, :destroy ]
  resources :bookings, only: [ :show, :update, :destroy, :edit ] do
    resources :reviews, only: [:new, :create ]
  end

  post 'bookings/:id/accept', to: 'bookings#accept', as: :accept_booking
  post 'bookings/:id/deny', to: 'bookings#deny', as: :deny_booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #   get 'reviews/show'
  # get 'bookings/show'
  # get 'bikes/index'
  # get 'bikes/show'
  get 'user/:id', to: 'users#show', as: :profile
  get '/dashboard', to: 'pages#dashboard'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->

<div class="container-fluid footer bg-dark py-5">
  <ul style="list-style: none">
    <li style="margin-bottom: 5px">Copyright 2021 Spin Finder</li>
    <li>Made with ♥️ by Chris, Thomas, San, and Julian</li>
  </ul>
</div>

app/views/shared/_index.html.erb
<%  def cloudinary_imgs(key) %>
<%    cl_image_tag(key, :height=>200, :quality=>"auto", :fetch_format=>:auto, :transformation => { :dpr => "auto", :responsive => true, :width => "auto", :crop => "scale", }) %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-custom">
    <%= link_to "Spin Finder", root_path, class: "navbar-brand" %>
    <ul class="navbar-nav">
        <% if current_user == nil %>
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </ul>
    <% if current_user %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav d-flex flex-end mr-4">
            <li class="nav-item dropdown">
                <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else %>
                <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y" />
                <% end %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to "Home", root_path, class: "dropdown-item" %>
                    <%= link_to "Profile", dashboard_path, class: "dropdown-item" %>
                    <%= link_to "Add a new bike", new_bike_path, class: "dropdown-item" %>
                    <%= link_to "Rent a bike", bikes_path, class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
            </li>
        </ul>
    </div>
    <% end %>
</div>