config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'dashboard/index'
  devise_for :users
  root to: 'pages#home' # landing page => bike show

  resources :bikes do
    resources :bookings, only: [:new, :create ]
  end

  resources :reviews, only: [ :show, :update, :destroy ]
  resources :bookings, only: [ :show, :update, :destroy, :edit ] do
    resources :reviews, only: [:new, :create ]
  end

  post 'bookings/:id/accept', to: 'bookings#accept', as: :accept_booking
  post 'bookings/:id/deny', to: 'bookings#deny', as: :deny_booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #   get 'reviews/show'
  # get 'bookings/show'
  # get 'bikes/index'
  # get 'bikes/show'
  get 'user/:id', to: 'users#show', as: :profile
  get '/dashboard', to: 'pages#dashboard'
end

app/views/pages/dashboard.html.erb
<section id="dashboard">
    <div class="row py-2 px-5 mt-0">
        <div class="col-lg-12 col-md-12 mx-auto">
            <div class="bg-white shadow rounded overflow-hidden">
                <div class="px-4 pt-5 pb-4 cover">
                    <div class="media align-items-end profile-head">
                        <div class="profile mr-3">
                            <%= image_tag current_user.avatar, class:"img-fluid mb-2 img-thumbnail", style: "width: 130px;" %>
                            <!-- Edit Profile section? -->
                            <%= link_to "Edit Profile", edit_user_registration_path(@user), :class => 'btn btn-outline-dark btn-sm btn-block'%>
                        </div>
                        <div class="media-body mb-5 text-white">
                            <h4 class="mt-0 mb-0">
                                <%= @user.first_name %>
                                <%= @user.last_name %>
                            </h4>
                            <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>
                                <%= @user.location %>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="bg-light p-4 d-flex justify-content-end text-center">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <h5 class="font-weight-bold mb-0 d-block">
                                <%= @user.bookings.count %>
                            </h5>
                            <small class="text-muted"> <i class="fas fa-list-alt mr-1"></i>Rentals</small>
                        </li>
                        <li class="list-inline-item">
                            <h5 class="font-weight-bold mb-0 d-block">
                                <%= @user.bikes.count %>
                            </h5>
                            <small class="text-muted"> <i class="fas fa-bicycle mr-1"></i>Bikes</small>
                        </li>
                        <li class="list-inline-item">
                            <h5 class="font-weight-bold mb-0 d-block">340</h5>
                            <small class="text-muted"> <i class="fas fa-user mr-1"></i>Followers</small>
                        </li>
                    </ul>
                </div>
                <!-- About Section -->
                <div class="px-4 py-3">
                    <h5 class="mb-1">About</h5>
                    <div class="p-4 rounded shadow-sm bg-light">
                        <p class="font-italic mb-0">
                            <%= @user.email %>
                        </p>
                        <p class="font-italic mb-0">Lives in
                            <%= @user.location %>
                        </p>
                        <p class="font-italic mb-0">
                            <%= @user.bio %>
                        </p>
                    </div>
                </div>
                <!-- Display your own pending bookings -->
                <!-- Display current status -->
                <!-- Display bookings someone has made on your bikes -->
                <!-- Needs Accept/Reject button -->
                <div class="py-4 px-4">
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <h5 class="mb-1">Approve/Deny Bookings</h5>
                </div>
                 </div>

          <div class="container-fluid status-bookings d-flex flex-column">
            <% @requested_bookings.each do |booking| %>
              <div class="p-4 mb-3 rounded shadow-sm bg-light">
                  <div class="status-row border-bottom mb-2 d-flex justify-content-between">
                    <h5>Status </h5>

                    <% if booking.status == "Pending" %>
                      <h4 id="status-pending"><i class="fas fa-question-circle" style="color:grey;"></i></h4>
                    <% end %>

                    <% if booking.status == "Approved" %>
                      <h4 id="status-approved"><i class="fas fa-check-circle" style="color:green;"></i></h4>
                    <% elsif booking.status == "Denied" %>
                      <h4 id="status-denied"><i class="fas fa-times-circle" style="color:red;"></i></h4>
                    <% end %>
                  </div>
                  <p> <i class="fas fa-clock"></i> Expires: <%= booking.till.strftime("%d/%-m/%Y") %></p>
                  <% if booking.status == "Pending" %>
                    <%= link_to "Approve", accept_booking_path(booking), method: :post, class:"btn btn-success p-2", id:"button-approve"%>
                    <%= link_to "Deny", deny_booking_path(booking), method: :post, class:"btn btn-danger p-2", id:"button-deny"%>
                  <% end %>
              </div>
            <% end %>
          </div>
              
                    <!-- Listings -->
                    <div class="py-4 px-4">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <h5 class="mb-0">Your Bikes</h5>
                            <a href="#" class="btn btn-link text-muted">Show all</a>
                        </div>
                        <ul class="cards">
                            <% @user.bikes.each do |bike| %>
                            <li class="cards_item">
                                <!-- Listing Card -->
                                <div class="card">
                                    <!-- Card image -->
                                    <div class="card_image">
                                        <%= image_tag bike.images[0], class:"img-fluid", style:"height: 500; width: 300;" %>
                                    </div>
                                    <!-- Card body -->
                                    <div class="card_content">
                                        <h4 class="card_title mb-3">
                                            <%= bike.name %>
                                        </h4>
                                        <div class="price-wrap d-flex justify-content-between">
                                            <p><i class="fas fa-dollar-sign"></i>
                                                <%= bike.price %> per / day
                                            </p>
                                            <p><i class="fas fa-star"></i></i>
                                                <%= bike.rating %>/5 (
                                                <%= bike.reviews.count %> )
                                            </p>
                                        </div>
                                        <hr>
                                        <div class="d-flex justify-content-end">
                                            <%= link_to "", bike_path(bike), class:"mb-2 mr-1 p-2 btn btn-outline-primary fas fa-info-circle"%>
                                            <%= link_to "", bike_path(bike), class: "mb-2 mr-1 p-2 btn btn-outline-danger fas fa-trash-alt", method: :delete, data: { confirm: "Are you sure?" } %>
                                            <%= link_to "", edit_bike_path(bike), class:"mb-2 p-2 btn btn-outline-warning fas fa-pencil-alt" %>
                                        </div>
                                        <!-- /bikes/152/edit -->
                                    </div>
                                </div>
                                <% end %>
                            </li>
                        </ul>
                    </div>
                    <hr>
                    <!-- Rentals/Bookings -->
                    <div class="py-4 px-4">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <h5 class="mb-0">Your Rentals</h5>
                            <a href="#" class="btn btn-link text-muted">Show all</a>
                        </div>
                        <ul class="cards">
                            <% @user.bookings.each do |booking| %>
                            <li class="cards_item">
                                <div class="card">
                                    <!-- Card image -->
                                    <div class="card_image">
                                        <%= image_tag booking.bike.images[0], class:"img-fluid", style:"height: 500; width: 300;" %>
                                    </div>
                                    <!-- Card body -->
                                    <div class="card_content">
                                        <h4 class="card_title mb-3">Rented -
                                            <%= booking.from.strftime("%d/%-m/%Y") %> -
                                            <%= booking.till.strftime("%d/%-m/%Y") %>
                                        </h4>
                                        <div class="price-wrap d-flex justify-content-between">
                                            <p> Total
                                                <i class="fas fa-dollar-sign"></i>
                                                <%= booking.total_price %>
                                            </p>
                                            <p><i class="fas fa-star"></i></i>
                                                <%= booking.bike.rating %>/5 (
                                                <%= booking.bike.reviews.count %> )
                                            </p>
                                        </div>
                                        <!-- Avatar image and Review link -->
                                        <div class="d-flex justify-content-between">
                                            <div>
                                                <%= link_to cloudinary_avatar_profile(booking.bike.user.avatar.key), profile_path(booking.bike.user.id) %>
                                            </div>
                                            <div class='text-center py-3'>
                                                <%= link_to "", bike_path(booking.bike), class:"p-2 btn btn-outline-dark fas fa-bicycle" %>
                                                <%= link_to '', new_booking_review_path(booking), class:"p-2 btn btn-outline-primary far fa-thumbs-up" %>
                                                <%= link_to "", booking_path(booking), class: "p-2 btn btn-outline-danger fas fa-trash-alt", method: :delete, data: { confirm: "Are you sure?" } %>
                                                <%= link_to "", edit_booking_path(booking), class:"p-2 btn btn-outline-warning fas fa-pencil-alt" %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <% end %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
</section>

app/views/pages/destinations.html.erb
<div id="destination-map" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
<div id='destinations'>
    <section id='beach-road' class='active section-destination-page'>
        <h3>Beach Road</h3>
        <p>Ah Beach Road – Melbourne cycling Mecca.
        Every Saturday and Sunday morning there are sure to be thousands of cyclists on the weekly pilgrimage to one of many destinations along the beach road in Melbourne’s southern suburbs along the bay. Beach Road offers cyclists of all levels of ability the chance to get out in the sunshine and enjoy views of our lovely Port Phillip Bay. For beginners, there is a bike path, whilst more confident riders can share the road with the other groups of cyclists. Be wary however, sometimes it can get rather crowded. Beach Road is so popular with cyclists many have taken to social media with the hashtag #notbeachroad to inform people when they’re riding a different route for a change!</p>
      <img src="https://cdn.shortpixel.ai/client/q_glossy,ret_img,w_1920/https://www.greatoceanroadaustralia.org/wp-content/uploads/2020/01/coen-van-den-broek-OFyh9TpMyM8-unsplash-1920x1080.jpg" class="image-destination-page">
    </section>
    <section id='yarra-blvd' class="section-destination-page">
        <h3>Yarra Boulevard</h3>
        <p>If you’re looking for a more serious work out, more hilly terrain or thigh testing riding, then Yarra Boulevard in Kew is the place to head.  A favourite for road riders, with little traffic and a dedicated bike lane throughout, the 13km loop gives you a 220m climb for each lap.  Choose from a single lap or multiple laps to achieve your workout goals, or test yourself further with many side-street options including Yarra Street which is a short but taxing 17% gradient in parts (that’s steep!!).</p>
      <img src="http://www.parks.vic.gov.au/-/media/project/pv/main/parks/images/places-to-see/yarra-bend-park/kanes-bridge-yarra-bend-park-1920x1124.jpg" class="image-destination-page">
    </section>
    <section id='dandenongs' class="section-destination-page">
        <h3>Dandenong Ranges</h3>
        <p>The Dandenong Ranges are one of Melbourne’s most popular cycling playgrounds.  It’s an escape from the hustle and bustle of crazy city life and will take you into a world of hidden delights.  It’s so easy to fall in love with the Dandenong Ranges and has some of the greatest climbing that metropolitan Melbourne has to offer.</p>
      <img src="https://cyclingtips.com/wp-content/uploads/2020/12/smallMelbs_VV_a11i8409.jpg" class="image-destination-page">
    </section>
    <section id='lysterfield' class="section-destination-page">
        <h3>Lysterfield Park</h3>
        <p>Lysterfield Park is one of the best places to mountain bike close to Melbourne. Undulating trails flow up and down steep hills and through dense plantations. Outcroppings of large boulders add to the scenic attraction - and to the challenge of the trails.

        The State Mountain Bike Course, used for the 2006 Commonwealth Games, offers tight single tracks, technical rocky sections, high speed descents with inclined berms, timber boardwalks and steep hill climbs. Aneurysm is a favourite that combines jumps, drops and man-made obstacles. Both are for experienced riders.
        </p>
      <img src="http://www.parks.vic.gov.au/-/media/project/pv/main/parks/images/things-to-do/mountain-biking/mtb-kinglake-national-park-1920x1124.jpg" class="image-destination-page">
    </section>
</div>

app/views/pages/home.html.erb
<!-- Header Container with Search Bar and Title -->
<div class="container-fluid header d-flex">
    <div class="page-header d-flex">
        <h1>Search for places to ride a <span>bike.</span></h1>
        <%= simple_form_for :search, url: bikes_path, method: :get do |f| %>
        <div class="search-form-control form-group">
            <input class="form-control string required" placeholder="E.g. Richmond, Victoria" type="text" name="search[query]" id="search_query" />
            <button name="button" type="submit" class="btn btn-dark mt-3">
                <i class="fas fa-search"></i> Search</button>
        </div>
        <% end %>
    </div>
</div>

<!-- Need to iterate through User Bike images (limit 8) -->


<!-- Image grid for popular bikes -->
<div class="container container-popular-bikes my-5">
    <h3 class="font-weight-light text-center text-lg-left mt-4 mb-0">Popular Bikes</h3>
    <div class="row">
    <% @bikes.take(8).each do |bike| %>
        <div class="col-lg-3 col-md-4 col-6 card-bike-category p-1">
          <div class="card-overlay p-2">
            <p><%= bike.name %></p>
            <p>$<%= bike.price %> / hour </p>
            <%= link_to 'View', bike_path(bike), class:"btn-block btn-primary p-2 w-50 text-center" %>
          </div>
          <%= image_tag bike.images[0], class:"img-fluid w-100" %>
        </div>
        <% end %>
    </div>
</div>

<!-- Scrolling JS Map of good cycling spots in each city -->
<!-- Turn each card into a link to a new view -->

<!-- Destination Section -->


<section class="card-large-destination">
    <div class="container">
        <h3 class="font-weight-light text-center text-lg-left mt-4 mb-0">Great Destinations</h3>
        <div class="row">
            <!--  Melbourne  -->
            <div class="column mb-3">
                <img src="https://source.unsplash.com/g0gHGCAMclI/500x550" class="img-fluid" alt="Melbourne" style="width:100%">
                <br>
                <h5>Melbourne</h5>
            </div>
            <!--  Sydney  -->
            <div class="column">
                <img src="https://source.unsplash.com/FUh6nK3s0po/500x550" class="img-fluid" alt="Sydney" style="width:100%">
                <br>
                <h5>Sydney</h5>
            </div>
            <!--  Perth  -->
            <div class="column">
                <img src="https://source.unsplash.com/7QLfUdaZbQw/500x550" class="img-fluid" alt="Perth" style="width:100%">
                <br>
                <h5>Perth</h5>
            </div>
            <!--  Byron Bay  -->
            <div class="column">
                <img src="https://source.unsplash.com/HzfFMa14VoU/500x550" class="img-fluid" alt="Byron Bay" style="width:100%">
                <br>
                <h5>Byron Bay</h5>
            </div>
        </div>
    </div>
</section>