config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'dashboard/index'
  devise_for :users
  root to: 'pages#home' # landing page => bike show

  resources :bikes do
    resources :bookings, only: [:new, :create ]
  end

  resources :reviews, only: [ :show, :update, :destroy ]
  resources :bookings, only: [ :show, :update, :destroy, :edit ] do
    resources :reviews, only: [:new, :create ]
  end

  post 'bookings/:id/accept', to: 'bookings#accept', as: :accept_booking
  post 'bookings/:id/deny', to: 'bookings#deny', as: :deny_booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #   get 'reviews/show'
  # get 'bookings/show'
  # get 'bikes/index'
  # get 'bikes/show'
  get 'user/:id', to: 'users#show', as: :profile
  get '/dashboard', to: 'pages#dashboard'
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  geocoded_by :address

  # has_many :favourites, dependent: :destroy

  ## through ass
  has_many :reviews, through: :bookings, dependent: :destroy

  ## validations :
  validates :description, length: { maximum: 500, too_long: "%{count} characters is the maximum allowed" }
  validates :rating, numericality: { only_float: true }
  validates :address, presence: true
  validates :price, presence: true
  validates :times_booked, numericality: { only_integer: true }
  after_validation :geocode, if: :will_save_change_to_address?
  ## Images
  has_many_attached :images

  def unavailable_dates
    bookings.pluck(:from, :till).map do |range|
      { from: range[0], to: range[1] }
    end
  end

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  def index
    # params from HOME
    if params.has_key?(:search) && params[:search][:query].present?
      @results = Geocoder.search(params[:search][:query]).first.coordinates
      # find bikes NEAR the geo
      # @bikes is now ready to parse =>
      @bikes = policy_scope(Bike).near(@results, 20)
      # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
      @markers = @bikes.geocoded.map do |bike|
        {
          lat: bike.latitude,
          lng: bike.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { bike: bike })
        }
      end

    else
      @bikes = policy_scope(Bike).order(created_at: :desc)
      @markers = @bikes.geocoded.map do |bike|
        {
          lat: bike.latitude,
          lng: bike.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { bike: bike })
        }
      end
    end
  end

  def show
    # set with :set_bike
    @booking = Booking.new
    @user = current_user
    @review = Review.new()
  end

  def new
    @bike = Bike.new

    authorize @bike ## this is in set_rest
  end

  def create
    # @bike.errors.full_messages
    @user = current_user.id
    @bike = Bike.new(bike_params)
    @bike.update(rating: 0, user_id: @user)
    @bike.images.attach(params[:bike][:images])

    authorize @bike

    #raise
    if @bike.valid?
      @bike.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    # gets set

  end

  def update
    # gets set

    @user = current_user.id
    # @bike = Bike.new(bike_params)
    # @bike = Bike.update!(rating: 0)
    # @bike.images.attach(params[:bike][:images])
    authorize @bike
    if @bike.valid?
      @bike.update(bike_params)
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    # gets set
    @bike.destroy
    # no need for app/views/Bikes/destroy.html.erb
    redirect_to dashboard_path
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
    authorize @bike
  end

  def bike_params
    params.require(:bike).permit( :price, :rating, :name,  :description, :address, :user_id, images: [])
  end

  def has_reviews?
    @bike.review_ids.last = nil
    return '<%= link_to "Add Review", new_bike_review_path(@bike) , class: "btn card-link " %>'
  end
end

app/views/bikes/_info_window.html.erb
<div class="container">
    <h3>
        <%= bike.name %>
    </h3>
    <p>
        <%= bike.address %>
    </p>
    <%= link_to cloudinary_imgs(bike.images[0].key,bike), bike_path(bike) %>
</div>

app/views/bikes/_new_bike_form.html.erb
<div class="container mx-auto py-2">
    <%= simple_form_for [ @bike ] do |f| %>
    <%= f.input :name, placeholder: 'Give your bike a funky name', required: true  %>
    <%= f.input :description, as: :text, placeholder: 'Description of your bike', required: true  %>
    <%= f.input :price, placeholder: 'Price per hour', input_html: { min: '1' }, required: true   %>
    <%= f.input :address, input_html: { :id => 'search_query' }, required: true  %>
    <%=  f.input :images, as: :file, input_html: { multiple: true }, required: true  %>
    <%= f.submit "Submit Bike", class: "btn btn-primary my-2" %>
    <% end %>
</div>

app/views/bikes/edit.html.erb
<div class="container mx-auto py-2">
    <%= render "new_bike_form", bike: @bike %>
</div>

app/views/bikes/index.html.erb
<div class="container-fluid m-0 p-0">
  <!--   start row  -->
  <div class="row p-0 m-0">
    <div class="col-lg-6 col-md-6 col-sm-12 p-0 m-0 ">
      <!-- Map on the left -->
      <div class="container-map">
        <!-- Need to put map in here -->
        <div id="map" style="width: 100%; height: 100vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
    <!-- Bikes on the right column -->
    <div class="col-lg-6 col-md-6 col-sm-12 p-2 ">
      <div class="container-bikes">
        <div class="row m-0">
          <% @bikes.each do |bike| %>
            <div class="col-md-6 border p-2 ">
              <div class="card card-bikes">
                <%= cloudinary_imgs(bike.images[0].key,bike) %>
                <div class="card-body">
                  <h5 class="card-title">
                    <%= bike.name %>
                  </h5>
                  <p class="card-text text-muted">
                    $
                    <%= bike.price %> / hour
                  </p>
                  <%= link_to "More Info", bike_path(bike) , class: "btn btn-outline-info" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bikes/new.html.erb
<div class="container">
  <div class="row mx-auto my-3 justify-content-center">
    <div class="col-6 mt-5">
      <h1>Add Your New Bike</h1>
      <%= render "new_bike_form", bike: @bike %>
    </div>
  </div>
</div>

app/views/bikes/show.html.erb
<div class="container font-weight-light">
    <!--CAROUSEL -->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <% @bike.images.each.with_index(0) do |post, index| %>
            <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>"></li>
            <% end %>
        </ol>
        <div class="carousel-inner">
            <% @bike.images.each.with_index(0) do |bike, index| %>
            <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
                <%= link_to "#" do %>
                <%= cloudinary_imgs_cara(bike.key,@bike) %>
                <% end %>
            </div>
            <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <!--NAME -->
    <div class="inner">
        <div class="name m-3">
            <h3><strong>
                    <!--               <i class=" mr-5 fas fa-bicycle"></i>
 -->
                    <%= @bike.name  %></strong></h3>
        </div>
        <div class="name-avail text-center">
            <div class="avail">
                <% if @bike.available == true %>
                <h6 style="color:##2ECC40">Bike is available</h6>
                <% else %>
                <h6 style="color:#FF4136">Bike is unavailable</h6>
                <% end %>
            </div>
        </div>
        <div class="row justify-content-center parent">
            <!-- CARD -->
            <div class="details sticky p-3 m-3 text-center col-sm-3">
                <h5>
                    <i style="color:#2ECC40" class="fas fa-dollar-sign"></i>
                    <%= @bike.price.to_i %> / hr</h5>
                <hr>
                <h5> <i style="color:#036CE7" class="fas fa-globe-asia"></i> Find me at:</h5>
                <h6>
                    <%= @bike.address  %>
                </h6>
                <hr>
                <h5>Rating <i style="color:#FF851B" class="far fa-star"></i> / 5</h5>
                <h6>
                    <% if @bike.rating == 0 %>
                    Bike has no reviews
                    <% else %>
                    <%= @bike.rating %> / 5 </h6>
                <% end %>
                <hr>
                <%= link_to "Ride!", new_bike_booking_path(@bike), class:" btn-lg btn-primary" %>
            </div>
            <!--DESCRIPTION-->
            <div class="content col-8 ">
                <div class="description p-3 m-3">
                    <h5><strong>Description</strong> <i class=" ml-5 fas fa-bicycle"></i> </h5>
                    <hr>
                    <%= @bike.description  %>
                </div>
                <!--       Booking Form -->
                <div class="description p-3 m-3" id='bike-booking-dates' data-unavailable="<%= @bike.unavailable_dates.to_json %>">
                    <% unless current_user.nil? %>
                    <% if current_user.id != @bike.user_id  %>
                    <h5><strong>Book
                            <%= @bike.name  %></strong></h5>
                    <%= simple_form_for([@bike, @booking]) do |f| %>
                    <%= f.input :from, as: :string, type: :text %>
                    <%= f.input :till, as: :string, type: :text %>
                    <%= f.submit "Book", class: "btn btn-primary" %>
                    <% end %>
                    <% end %>
                    <% end %>
                </div>
                <!-- REVIEWS IF BOOKED -->
                <div class="review-form p-3 m-3">
                    <% @bike.bookings.each do |booking| %>
                    <% unless current_user.nil? %>
                    <% if booking.user_id == current_user.id %>
                    <h5><strong>Last booking
                            <%= booking.from.strftime("%d/%-m/%Y") %></strong></h5>
                    <hr>
                    <h4>Add a Review</h4>
                    <%= simple_form_for([booking, @review], remote: true) do |f| %>
                    <%= f.input :content, placeholder: 'How was your ride ?', required: true  %>
                    <%= f.input :rating, placeholder: 'Score 1 - 5', input_html: { min: '1', max: '5' }, required: true  %>
                    <%= f.submit class: "btn btn-primary" %>
                    <% end %>
                    <% end %>
                    <% end %>
                    <% end %>
                </div>
                <!-- REVIEWS -->
                <div class="reviews p-3 m-3">
                    <h5><strong>Reviews</strong></h5>
                    <hr>
                    <% @bike.reviews.reverse.each do |review| %>
                    <div class="single-review"id="review-<%= review.id %>">
                        <div class="card text-white bg-secondary mb-3 p-3">
                            <h5>Comment</h5>
                            <p>
                                <%= review.content %>
                            </p>
                            <h5>Rating</h5>
                            <h5>
                                <%= review.rating.to_i %> / 5</h5>
                                <div class="text-right">
                                <% if current_user && review.booking.user_id == current_user.id %>
                                <%= link_to "", review_path(review), method: :delete, data: { confirm: "Are you sure?" }, remote: true, class: " btn btn-outline-danger fas fa-trash-alt" %>
                                <% end %>

                                </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>